### ISSUE TITLE
Add Github link to the bottom of the index page.

### ISSUE THREAD

**Issue by gp185095** [NCR-Corporation/sample-app-burgers#8]
I think it would be a good idea to add the github link to the bottom of the index page and maybe to the doc resources as well.

@tm185221

**Comment by rb185333** [comment]
@gp185095 I just opened a [PR with some design changes](https://github.com/NCR-Corporation/sample-app-burgers/pull/9) that included adding some GitHub links on the sample app site earlier today. Here are some screenshots for reference:

<img width="1283" alt="Screen Shot 2020-11-11 at 5 12 46 PM" src="https://user-images.githubusercontent.com/68287936/98870501-60c61300-2441-11eb-9611-8011b70a5819.png">

<img width="1325" alt="Screen Shot 2020-11-11 at 5 17 39 PM" src="https://user-images.githubusercontent.com/68287936/98870869-ecd83a80-2441-11eb-9ce9-3ebe96fa900d.png">

<img width="1324" alt="Screen Shot 2020-11-11 at 5 18 52 PM" src="https://user-images.githubusercontent.com/68287936/98870957-15603480-2442-11eb-9e11-8f9933b54c39.png">

**Comment by gp185095** [comment]
I like it! Thanks.
